// <auto-generated />
using BackgroundJobs.UsingHangfire.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackgroundJobs.UsingHangfire.Api.Migrations
{
    [DbContext(typeof(HangfireDbContext))]
    partial class HangfireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackgroundJobs.UsingHangfire.Api.Models.EmailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailMessages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Hello!\r\nThank you for applying to the Senior Software Engineer (.Net Full Stack and Azure/AWS) position at EPAM India. You have an impressive resume, and it was a pleasure to learn more about your skills and accomplishments.\r\n\r\nHowever, we regret to inform you that we have decided to not pursue your candidature currently due to the location demands of the role. But now that we have had the chance to know more about you, we would like to keep your resume on file for future openings that may better fit your profile and location.\r\n\r\nIn the meantime, feel free to apply to other suitable positions on our careers page. Thank you for considering EPAM to be a part of your career journey.\r\n\r\nWe wish you good luck in your job search and all future endeavours.\r\n\r\nRegards,\r\n\r\nTeam EPAM India",
                            HtmlContext = "<!DOCTYPE html>\r\n                            <html>\r\n                            <head>\r\n                                <meta charset='UTF-8'>\r\n                                <title>Email Message</title>\r\n                            </head>\r\n                            <body>\r\n                                <p>Hello!</p>\r\n                                <p>Thank you for applying to the Senior Software Engineer (.Net Full Stack and Azure/AWS) position at EPAM India. You have an impressive resume, and it was a pleasure to learn more about your skills and accomplishments.</p>\r\n                                <p>However, we regret to inform you that we have decided to not pursue your candidature currently due to the location demands of the role. But now that we have had the chance to know more about you, we would like to keep your resume on file for future openings that may better fit your profile and location.</p>\r\n                                <p>In the meantime, feel free to apply to other suitable positions on our careers page. Thank you for considering EPAM to be a part of your career journey.</p>\r\n                                <p>We wish you good luck in your job search and all future endeavors.</p>\r\n                                <p>Regards,</p>\r\n                                <p>Team EPAM India</p>\r\n                            </body>\r\n                            </html>",
                            Subject = "Your application results"
                        });
                });

            modelBuilder.Entity("BackgroundJobs.UsingHangfire.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "mattmadjitey@gmail.com",
                            Name = "Matthew Oduamafu",
                            PhoneNumber = "0552474843"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "mattoduamafu@hotmail.com",
                            Name = "Matt Oduamafu",
                            PhoneNumber = "0552235521"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
